### ISSUE TITLE
CONTRIBUTING.md suggestions

### ISSUE THREAD

**Issue by cvrebert** [w3c/uievents-key#21]
> To make substantive contributions to specifications, you must either participate in the relevant W3C Working Group or make a non-member patent licensing commitment.

I would recommend:
- hyperlinking "make a non-member patent licensing commitment" to https://www.w3.org/2004/01/pp-impl/83482/nmlc
- mentioning that Web Platform Working Group is the relevant WG
  - including a link to https://www.w3.org/WebPlatform/WG/

**Comment by garykac** [comment]
Fixed in the uievents and uievents-code repos as well.

**Comment by cvrebert** [comment]
:smile:
