### ISSUE TITLE
No differences between "AudioBassDown", "AudioBassUp" and "AudioBassBoostDown", "AudioBassBoostUp"?

### ISSUE THREAD

**Issue by masayuki-nakano** [w3c/uievents-key#25]
"AudioBassDown"     Decrease bass. (APPCOMMAND_BASS_DOWN) 
"AudioBassBoostDown"    Decrease audio bass boost or cycle down through bass boost states. (VK_BASS_BOOST_DOWN) 

It seems that they can be merged.

And also

"AudioBassBoostUp"  Increase audio bass boost or cycle up through bass boost states. (VK_BASS_BOOST_UP) 
"AudioBassUp"   Increase bass. (APPCOMMAND_BASS_UP) 

"AudioBassDown" and "AudioBassUp" are defined only for APPCOMMAND of Windows. And Windows doesn't have virtual key code values about BassDown/Up. So, I think that AudioBassDown and AudioBassUp can be dropped from the spec.

Chromium already defined them, though:
https://code.google.com/p/chromium/codesearch#chromium/src/ui/events/keycodes/dom/dom_key_data.inc&q=AudioBass&sq=package:chromium&type=cs&l=319

**Comment by masayuki-nakano** [comment]
FYI: "AudioBassBoostToggle" is also there, but not conflicted with the others. "Boost" sounds redundant but audio key names are named from the VK names. So, I think that the spec should keep using "Boost" for consistency with other similar keys.

**Comment by garykac** [comment]
Yes, that sounds right.

See http://crrev.com/2642963002 for Chrome change
