### ISSUE TITLE
It's odd KEYCODE_MEDIA_CLOSE of Android is mapped to "Close"

### ISSUE THREAD

**Issue by masayuki-nakano** [w3c/uievents-key#26]
It's odd KEYCODE_MEDIA_CLOSE of Android is mapped to "Close". "Close" is used for multimedia keyboard's close key which closes current document or tab as explained by the spec. However, KEYCODE_MEDIA_CLOSE is explained as "Key code constant: Close media key. May be used to close a CD tray, for example. " by Android's document (https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_MEDIA_CLOSE).

So, if web browsers map the key code to "Close", the key value has double meaning across platforms.

**Comment by garykac** [comment]
Yes, APPCOMMAND_CLOSE and KEYCODE_MEDIA_CLOSE should be 2 separate values.

I think the following makes sense:
"Close" APPCOMMAND_CLOSE
"MediaClose" KEYCODE_MEDIA_CLOSE

**Comment by garykac** [comment]
See http://crrev.com/2641073002 for Chome update
