### ISSUE TITLE
Indicate that Hyper and Super keys are legacy

### ISSUE THREAD

**Issue by cvrebert** [w3c/uievents-key#29]
To match the Code spec. See https://w3c.github.io/uievents-code/#key-legacy

**Comment by masayuki-nakano** [comment]
"Super" key and "Hyper" key are still mapped (and called as so) on X (i.e., UNIX and Linux).

We're still not sure what's the best value for Windows Logo key on X, though. See following bug and issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=936319
https://github.com/w3c/uievents/issues/28
https://bugs.chromium.org/p/chromium/issues/detail?id=613152

@garykac How do you think abut the proper key value of Super and Hyper key on Linux? On other platforms, we've already decided to use "Meta" for 'Command' key of Mac and 'Windows Logo' key of Windows.  However, on modern Linux, "Meta" key exists as Alt key with Shift. Should browsers ignore native "Meta" key code and use "Meta" key value for native "Super" and "Hyper" key code? (If so, we can drop "Super" and "Hyper" key values from the spec.)

**Comment by garykac** [comment]
I think that it's better to:
* Leave Meta alone on Linux - it'll still be generated via Shift-Alt
* Keep Super and Hyper as the values for the Super/Hyper keys.
* Move Super/Hyper to legacy, since they are not common on keyboards anymore

This will allow people to use them if they are available, while keeping Meta consistent with current usage. Note that people can remap Super -> Meta if they want.

**Comment by masayuki-nakano** [comment]
@garykac I have some question for clarify.

1. Browser should set the key value to "Meta" when Shift + Alt is pressed (and only when it causes "Meta" key event) only on Linux?
2. Browser should activate "Alt" modifier state when Alt is pressed, however, both "Alt" and "Meta" state should be activated when Shift + Alt is pressed?
3. Browser should activate "Super" modifier state when GUI key (Win Logo key) is pressed on Linux? (Although, it causes activating "Meta" state on other platforms).
