### ISSUE TITLE
Maybe odd mapping "KanaMode" to KEYCODE_KANA of Android

### ISSUE THREAD

**Issue by masayuki-nakano** [w3c/uievents-key#30]
Current draft declares:
https://w3c.github.io/uievents-key/#key-KanaMode
"KanaMode" 	The Kana Mode (Kana Lock) key. (KEYCODE_KANA) 

This is mapped to "Kana" key of JIS Mac keyboard.
https://www.google.co.jp/search?q=JIS+Mac+keyboard&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjkls7n2rnQAhXFEbwKHV1TC50Q_AUICCgB&biw=1484&bih=864#imgrc=FANsxJJTjRJmhM%3A

This switches inputting mode from any to "Hiragana" keyboard layout. However, the purpose of inputting Hiragana here is, for converting to Kanji characters from Hiragana.

At inputting Japanese text, most users use "Roman Character Input Mode". For example, typing "ai" converted to "あい" automatically. This is Hiragana characters represented by "ai". Then, typing space key or "Convert" key converts it to Kanji characters such as "愛", "亜衣", "藍", etc.

All browsers on Windows maps such key switching any mode to "KanjiMode". "KanaMode" is used for opposite key as "Romaji". So, this changes the input mode of Hiragana characters between Roman Characters vs. Hiragana Characters.

Additionally, KEYCODE_KANA works as "KanjiMode" on Windows. So, I think that "KanjiMode" is better key value for "KEYCODE_KANA".

**Comment by chong-z** [comment]
@garykac Do we have an update on this issue? Currently Gecko maps `AKEYCODE_KANA (218)` to `"KanjiMode"` and Blink maps it to `"KanaMode"`.

**Comment by garykac** [comment]
sgtm. I updated the spec to match Masayuki's suggestion
