### ISSUE TITLE
Faulty references

### ISSUE THREAD

**Issue by r12a** [w3c/uievents-key#32]
1. Introduction

https://w3c.github.io/uievents-key/#introduction

> see code described in [UIEvents-Code].

the reference section only contains

> [UIEVENTS-KEY]
>     Gary Kacmarcik; Travis Leithead. UI Events KeyboardEvent key Values. 15 December 2015. WD. URL: https://w3c.github.io/uievents-key/

**Comment by garykac** [comment]
[UIEvents-Code] is in the Informative References section.
