### ISSUE TITLE
i18n Issues common to main spec

### ISSUE THREAD

**Issue by r12a** [w3c/uievents-key#34]
The following issues were raised against the main UI Events spec, but are relevant to this spec also:

https://github.com/w3c/uievents/issues/127

https://github.com/w3c/uievents/issues/117

https://github.com/w3c/uievents/issues/121

**Comment by garykac** [comment]
Split into separate issues:
https://github.com/w3c/uievents-key/issues/35 - Use U+ notation to refer to code points
https://github.com/w3c/uievents-key/issues/36 - 'Key value' terminology is ambiguous and confusing
https://github.com/w3c/uievents-key/issues/37 - Printable control characters needs refinement
