### ISSUE TITLE
Definition of 'string'

### ISSUE THREAD

**Issue by xfq** [w3c/uievents-key#58]
Keyboard Event [key](http://www.w3.org/TR/uievents/#dom-keyboardevent-key) Attribute Values
https://w3c.github.io/uievents-key/#key-attr-values

> A key attribute value is defined as being a string that contains one of the following:

"String" is not clearly defined here. Is it a [DOMString](https://webidl.spec.whatwg.org/#idl-DOMString), an abstract string (which is not tied to a specific encoding), or anything else?

**Comment by LJWatson** [comment]
Ping @garykac. I believe this is the last outstanding issue before we can continue towards PR/Rec.

**Comment by LJWatson** [comment]
Pinging @garykac and @travisleithead to see if we can get this issue fixed so we can get this spec over the line?

**Comment by garykac** [comment]
The `key` attribute is not defined here. It is defined in the UIEvents spec, where it is explicitly defined as a DOMString.

But I'll change "string" to "DOMString" to be clear.

**Comment by xfq** [comment]
Thanks for the clarification!
