### ISSUE TITLE
CFC to publish UI Events KeyboardEvent key Values as a Proposed Recommendation  in the WebApps WG

### ISSUE THREAD

**Issue by siusin** [w3c/uievents-key#68]
The UI Events KeyboardEvent key Values spec has obtained [adequate implementation experience](https://w3c.github.io/uievents-key/impl-report.html), so this is a Call for Consensus to transition UI Events KeyboardEvent key Values to Proposed Recommendation.

The latest version of the spec is available at:
   http://www.w3.org/TR/uievents-key/

To show support for the transition, please add a 👍.

If you'd like to raise a Formal Objection to publishing this document, please do so by using a 👎 by 28 October, 2024.
Please include the rationale for your objection to its publication as GitHub comment or email the working group.

If you have other comments, suggestions, or found bugs, we invite you to file an issue.

**Comment by LJWatson** [comment]
With multiple expressions of support and no objections, the proposal to publish a PR of the UI Events KeyboardEvent key Values spec.
 

Thank you to everyone who responded.
