### ISSUE TITLE
For user-agents on Windows OS, map the "windows key" to Meta (instead of "OS")

### ISSUE THREAD

**Issue by travisleithead** [w3c/uievents-key#9]
For KeyboardEvent.key values on Windows OS, use "Meta" (instead of "OS"). This is for 1) better interop with Mac, 2) enabling general use of the `meta` attribute on KeyboardEvent.

See discussion at: https://github.com/w3c/uievents/issues/28#issuecomment-151028832

**Comment by garykac** [comment]
@masayuki-nakano

**Comment by masayuki-nakano** [comment]
I emailed to Olli (smaug) about this issue.

**Comment by smaug----** [comment]
I doubt "OS" has gained much use yet. This is of course backwards incompatible change.
The idea is that also .meta will be true with Windows-key?

**Comment by travisleithead** [comment]
Yes. Currently in IE9+ the .meta value is never true. :( I like the side-effect of making it work in Windows since it was a previously unused feature.

On backwards compatibility, yes, it is a breaking (not backwards-compatible) change. However, there is little current suspected use, and since IE9+ this has been the "Win" key name, so changing it to OS would be a breaking change for Edge too. I'd just assume go straight to "Meta".

**Comment by RByers** [comment]
I did an httpArchive search (top 500k sites) and found exactly 0 uses of `modifierOS` and `getModifierState("OS")` so I agree this is safe to change.

**Comment by RByers** [comment]
@travisleithead did you end up copying Chrome/Firefox here in Edge?  Looks like it sets 'OS' now.  We've [removed this from Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=539979) to match the spec, and @dtapuska is now cleaning up the remaining code.
